### ISSUE TITLE
Whitespace in field values

### ISSUE THREAD

**Issue by amellnik** [JuliaIO/ConfParser.jl#12]
Currently 

```ini
[default]
host="host"
user="admin"
pass="a password with spaces"
```

is parsed so that `pass` = `"a`.  It sounds like there's not a good standard for this -- could we change this to grab characters until the last cluster of whitespace at the end of the line?  Ie something like `/(\S+?)=([\s\S]+?)\s*$/`?  (I know that typically the values are not in quotes -- MySQL.jl just really wants to [feed them into parse](https://github.com/JuliaDB/MySQL.jl/blob/master/test/runtests.jl) for some reason.

**Comment by zznop** [comment]
Hash your passwords :)

**Comment by amellnik** [comment]
Do you think that's necessary in a case like https://github.com/JuliaDB/MySQL.jl/blob/master/test/server.ini where it's used to run tests locally and on Travis? Passwords aside, it seems like people might want to include other values in spaces in config file.

**Comment by zznop** [comment]
Just recommending a quick fix in the event passwords are the sole reason for your request. I’m for the new feature, but it needs implemented in such a way that it won’t negatively impact existing functionality. For example, you can currently comma separate values and ConfParser will parse them into an array:
```
foo=bar, foo
```
Your fix would break that paradigm and cause `bar, foo` to be treated as a single value. I think that in order to do this correctly, we need to add support for handling quotations and treat everything inside of the opening and closing quotations as a single preformatted value.
